#!/usr/bin/env python3
"""
Note: The contents of the current file have been automatically
generated by the "utils/hermes_bytecode_structs_parser.py"
script

Please do not edit it manually. 👍
"""

from typing import List, Set, Dict, Union, Optional, Sequence, Any

# Imports from the current diretory
from .def_classes import *

_instructions: List[Instruction] = []

Reg8 = OperandType('Reg8', 'uint8_t')
Reg32 = OperandType('Reg32', 'uint32_t')
UInt8 = OperandType('UInt8', 'uint8_t')
UInt16 = OperandType('UInt16', 'uint16_t')
UInt32 = OperandType('UInt32', 'uint32_t')
Addr8 = OperandType('Addr8', 'int8_t')
Addr32 = OperandType('Addr32', 'int32_t')
Imm32 = OperandType('Imm32', 'int32_t')
Double = OperandType('Double', 'double')

Unreachable = Instruction('Unreachable', 0, [], globals())

NewObjectWithBuffer = Instruction(
    'NewObjectWithBuffer', 1, [Reg8, UInt16, UInt16], globals()
)

NewObjectWithBufferLong = Instruction(
    'NewObjectWithBufferLong', 2, [Reg8, UInt32, UInt32], globals()
)

NewObject = Instruction('NewObject', 3, [Reg8], globals())

NewObjectWithParent = Instruction(
    'NewObjectWithParent', 4, [Reg8, Reg8], globals()
)

NewArrayWithBuffer = Instruction(
    'NewArrayWithBuffer', 5, [Reg8, UInt16, UInt16, UInt16], globals()
)

NewArrayWithBufferLong = Instruction(
    'NewArrayWithBufferLong', 6, [Reg8, UInt16, UInt16, UInt32], globals()
)

NewArray = Instruction('NewArray', 7, [Reg8, UInt16], globals())

Mov = Instruction('Mov', 8, [Reg8, Reg8], globals())

MovLong = Instruction('MovLong', 9, [Reg32, Reg32], globals())

Negate = Instruction('Negate', 10, [Reg8, Reg8], globals())

Not = Instruction('Not', 11, [Reg8, Reg8], globals())

BitNot = Instruction('BitNot', 12, [Reg8, Reg8], globals())

TypeOf = Instruction('TypeOf', 13, [Reg8, Reg8], globals())

Eq = Instruction('Eq', 14, [Reg8, Reg8, Reg8], globals())

StrictEq = Instruction('StrictEq', 15, [Reg8, Reg8, Reg8], globals())

Neq = Instruction('Neq', 16, [Reg8, Reg8, Reg8], globals())

StrictNeq = Instruction('StrictNeq', 17, [Reg8, Reg8, Reg8], globals())

Less = Instruction('Less', 18, [Reg8, Reg8, Reg8], globals())

LessEq = Instruction('LessEq', 19, [Reg8, Reg8, Reg8], globals())

Greater = Instruction('Greater', 20, [Reg8, Reg8, Reg8], globals())

GreaterEq = Instruction('GreaterEq', 21, [Reg8, Reg8, Reg8], globals())

Add = Instruction('Add', 22, [Reg8, Reg8, Reg8], globals())

AddN = Instruction('AddN', 23, [Reg8, Reg8, Reg8], globals())

AddS = Instruction('AddS', 24, [Reg8, Reg8, Reg8], globals())

Mul = Instruction('Mul', 25, [Reg8, Reg8, Reg8], globals())

MulN = Instruction('MulN', 26, [Reg8, Reg8, Reg8], globals())

Div = Instruction('Div', 27, [Reg8, Reg8, Reg8], globals())

DivN = Instruction('DivN', 28, [Reg8, Reg8, Reg8], globals())

Mod = Instruction('Mod', 29, [Reg8, Reg8, Reg8], globals())

Sub = Instruction('Sub', 30, [Reg8, Reg8, Reg8], globals())

SubN = Instruction('SubN', 31, [Reg8, Reg8, Reg8], globals())

LShift = Instruction('LShift', 32, [Reg8, Reg8, Reg8], globals())

RShift = Instruction('RShift', 33, [Reg8, Reg8, Reg8], globals())

URshift = Instruction('URshift', 34, [Reg8, Reg8, Reg8], globals())

BitAnd = Instruction('BitAnd', 35, [Reg8, Reg8, Reg8], globals())

BitXor = Instruction('BitXor', 36, [Reg8, Reg8, Reg8], globals())

BitOr = Instruction('BitOr', 37, [Reg8, Reg8, Reg8], globals())

Inc = Instruction('Inc', 38, [Reg8, Reg8], globals())

Dec = Instruction('Dec', 39, [Reg8, Reg8], globals())

InstanceOf = Instruction('InstanceOf', 40, [Reg8, Reg8, Reg8], globals())

IsIn = Instruction('IsIn', 41, [Reg8, Reg8, Reg8], globals())

GetParentEnvironment = Instruction(
    'GetParentEnvironment', 42, [Reg8, UInt8], globals()
)

GetEnvironment = Instruction(
    'GetEnvironment', 43, [Reg8, Reg8, UInt8], globals()
)

GetClosureEnvironment = Instruction(
    'GetClosureEnvironment', 44, [Reg8, Reg8], globals()
)

StoreToEnvironment = Instruction(
    'StoreToEnvironment', 45, [Reg8, UInt8, Reg8], globals()
)

StoreToEnvironmentL = Instruction(
    'StoreToEnvironmentL', 46, [Reg8, UInt16, Reg8], globals()
)

StoreNPToEnvironment = Instruction(
    'StoreNPToEnvironment', 47, [Reg8, UInt8, Reg8], globals()
)

StoreNPToEnvironmentL = Instruction(
    'StoreNPToEnvironmentL', 48, [Reg8, UInt16, Reg8], globals()
)

LoadFromEnvironment = Instruction(
    'LoadFromEnvironment', 49, [Reg8, Reg8, UInt8], globals()
)

LoadFromEnvironmentL = Instruction(
    'LoadFromEnvironmentL', 50, [Reg8, Reg8, UInt16], globals()
)

GetGlobalObject = Instruction('GetGlobalObject', 51, [Reg8], globals())

GetNewTarget = Instruction('GetNewTarget', 52, [Reg8], globals())

CreateFunctionEnvironment = Instruction(
    'CreateFunctionEnvironment', 53, [Reg8, UInt8], globals()
)

CreateTopLevelEnvironment = Instruction(
    'CreateTopLevelEnvironment', 54, [Reg8, UInt32], globals()
)

CreateEnvironment = Instruction(
    'CreateEnvironment', 55, [Reg8, Reg8, UInt32], globals()
)

DeclareGlobalVar = Instruction('DeclareGlobalVar', 56, [UInt32], globals())

DeclareGlobalVar.operands[0].operand_meaning = OperandMeaning.string_id

GetByIdShort = Instruction(
    'GetByIdShort', 57, [Reg8, Reg8, UInt8, UInt8], globals()
)

GetById = Instruction('GetById', 58, [Reg8, Reg8, UInt8, UInt16], globals())

GetByIdLong = Instruction(
    'GetByIdLong', 59, [Reg8, Reg8, UInt8, UInt32], globals()
)

GetByIdShort.operands[3].operand_meaning = OperandMeaning.string_id

GetById.operands[3].operand_meaning = OperandMeaning.string_id

GetByIdLong.operands[3].operand_meaning = OperandMeaning.string_id

TryGetById = Instruction(
    'TryGetById', 60, [Reg8, Reg8, UInt8, UInt16], globals()
)

TryGetByIdLong = Instruction(
    'TryGetByIdLong', 61, [Reg8, Reg8, UInt8, UInt32], globals()
)

TryGetById.operands[3].operand_meaning = OperandMeaning.string_id

TryGetByIdLong.operands[3].operand_meaning = OperandMeaning.string_id

PutByIdLoose = Instruction(
    'PutByIdLoose', 62, [Reg8, Reg8, UInt8, UInt16], globals()
)

PutByIdStrict = Instruction(
    'PutByIdStrict', 63, [Reg8, Reg8, UInt8, UInt16], globals()
)

PutByIdLooseLong = Instruction(
    'PutByIdLooseLong', 64, [Reg8, Reg8, UInt8, UInt32], globals()
)

PutByIdStrictLong = Instruction(
    'PutByIdStrictLong', 65, [Reg8, Reg8, UInt8, UInt32], globals()
)

PutByIdLoose.operands[3].operand_meaning = OperandMeaning.string_id

PutByIdStrict.operands[3].operand_meaning = OperandMeaning.string_id

PutByIdLooseLong.operands[3].operand_meaning = OperandMeaning.string_id

PutByIdStrictLong.operands[3].operand_meaning = OperandMeaning.string_id

TryPutByIdLoose = Instruction(
    'TryPutByIdLoose', 66, [Reg8, Reg8, UInt8, UInt16], globals()
)

TryPutByIdStrict = Instruction(
    'TryPutByIdStrict', 67, [Reg8, Reg8, UInt8, UInt16], globals()
)

TryPutByIdLooseLong = Instruction(
    'TryPutByIdLooseLong', 68, [Reg8, Reg8, UInt8, UInt32], globals()
)

TryPutByIdStrictLong = Instruction(
    'TryPutByIdStrictLong', 69, [Reg8, Reg8, UInt8, UInt32], globals()
)

TryPutByIdLoose.operands[3].operand_meaning = OperandMeaning.string_id

TryPutByIdStrict.operands[3].operand_meaning = OperandMeaning.string_id

TryPutByIdLooseLong.operands[3].operand_meaning = OperandMeaning.string_id

TryPutByIdStrictLong.operands[3].operand_meaning = OperandMeaning.string_id

PutNewOwnByIdShort = Instruction(
    'PutNewOwnByIdShort', 70, [Reg8, Reg8, UInt8], globals()
)

PutNewOwnById = Instruction(
    'PutNewOwnById', 71, [Reg8, Reg8, UInt16], globals()
)

PutNewOwnByIdLong = Instruction(
    'PutNewOwnByIdLong', 72, [Reg8, Reg8, UInt32], globals()
)

PutNewOwnByIdShort.operands[2].operand_meaning = OperandMeaning.string_id

PutNewOwnById.operands[2].operand_meaning = OperandMeaning.string_id

PutNewOwnByIdLong.operands[2].operand_meaning = OperandMeaning.string_id

PutOwnBySlotIdx = Instruction(
    'PutOwnBySlotIdx', 73, [Reg8, Reg8, UInt8], globals()
)

PutOwnBySlotIdxLong = Instruction(
    'PutOwnBySlotIdxLong', 74, [Reg8, Reg8, UInt32], globals()
)

PutNewOwnNEById = Instruction(
    'PutNewOwnNEById', 75, [Reg8, Reg8, UInt16], globals()
)

PutNewOwnNEByIdLong = Instruction(
    'PutNewOwnNEByIdLong', 76, [Reg8, Reg8, UInt32], globals()
)

PutNewOwnNEById.operands[2].operand_meaning = OperandMeaning.string_id

PutNewOwnNEByIdLong.operands[2].operand_meaning = OperandMeaning.string_id

PutOwnByIndex = Instruction(
    'PutOwnByIndex', 77, [Reg8, Reg8, UInt8], globals()
)

PutOwnByIndexL = Instruction(
    'PutOwnByIndexL', 78, [Reg8, Reg8, UInt32], globals()
)

PutOwnByVal = Instruction(
    'PutOwnByVal', 79, [Reg8, Reg8, Reg8, UInt8], globals()
)

DelByIdLoose = Instruction('DelByIdLoose', 80, [Reg8, Reg8, UInt16], globals())

DelByIdStrict = Instruction(
    'DelByIdStrict', 81, [Reg8, Reg8, UInt16], globals()
)

DelByIdLooseLong = Instruction(
    'DelByIdLooseLong', 82, [Reg8, Reg8, UInt32], globals()
)

DelByIdStrictLong = Instruction(
    'DelByIdStrictLong', 83, [Reg8, Reg8, UInt32], globals()
)

DelByIdLoose.operands[2].operand_meaning = OperandMeaning.string_id

DelByIdStrict.operands[2].operand_meaning = OperandMeaning.string_id

DelByIdLooseLong.operands[2].operand_meaning = OperandMeaning.string_id

DelByIdStrictLong.operands[2].operand_meaning = OperandMeaning.string_id

GetByVal = Instruction('GetByVal', 84, [Reg8, Reg8, Reg8], globals())

GetByIndex = Instruction('GetByIndex', 85, [Reg8, Reg8, UInt8], globals())

PutByValLoose = Instruction('PutByValLoose', 86, [Reg8, Reg8, Reg8], globals())

PutByValStrict = Instruction(
    'PutByValStrict', 87, [Reg8, Reg8, Reg8], globals()
)

DelByValLoose = Instruction('DelByValLoose', 88, [Reg8, Reg8, Reg8], globals())

DelByValStrict = Instruction(
    'DelByValStrict', 89, [Reg8, Reg8, Reg8], globals()
)

PutOwnGetterSetterByVal = Instruction(
    'PutOwnGetterSetterByVal', 90, [Reg8, Reg8, Reg8, Reg8, UInt8], globals()
)

GetPNameList = Instruction(
    'GetPNameList', 91, [Reg8, Reg8, Reg8, Reg8], globals()
)

GetNextPName = Instruction(
    'GetNextPName', 92, [Reg8, Reg8, Reg8, Reg8, Reg8], globals()
)

Call = Instruction('Call', 93, [Reg8, Reg8, UInt8], globals())
Call.has_ret_target = True

Construct = Instruction('Construct', 94, [Reg8, Reg8, UInt8], globals())
Construct.has_ret_target = True

Call1 = Instruction('Call1', 95, [Reg8, Reg8, Reg8], globals())
Call1.has_ret_target = True

CallWithNewTarget = Instruction(
    'CallWithNewTarget', 96, [Reg8, Reg8, Reg8, UInt8], globals()
)
CallWithNewTarget.has_ret_target = True

Call2 = Instruction('Call2', 97, [Reg8, Reg8, Reg8, Reg8], globals())
Call2.has_ret_target = True

Call3 = Instruction('Call3', 98, [Reg8, Reg8, Reg8, Reg8, Reg8], globals())
Call3.has_ret_target = True

Call4 = Instruction(
    'Call4', 99, [Reg8, Reg8, Reg8, Reg8, Reg8, Reg8], globals()
)
Call4.has_ret_target = True

CallWithNewTargetLong = Instruction(
    'CallWithNewTargetLong', 100, [Reg8, Reg8, Reg8, Reg8], globals()
)
CallWithNewTargetLong.has_ret_target = True

CallBuiltin = Instruction('CallBuiltin', 101, [Reg8, UInt8, UInt8], globals())

CallBuiltinLong = Instruction(
    'CallBuiltinLong', 102, [Reg8, UInt8, UInt32], globals()
)

GetBuiltinClosure = Instruction(
    'GetBuiltinClosure', 103, [Reg8, UInt8], globals()
)

Ret = Instruction('Ret', 104, [Reg8], globals())

Catch = Instruction('Catch', 105, [Reg8], globals())

DirectEval = Instruction('DirectEval', 106, [Reg8, Reg8, UInt8], globals())

Throw = Instruction('Throw', 107, [Reg8], globals())

ThrowIfEmpty = Instruction('ThrowIfEmpty', 108, [Reg8, Reg8], globals())

Debugger = Instruction('Debugger', 109, [], globals())

AsyncBreakCheck = Instruction('AsyncBreakCheck', 110, [], globals())

ProfilePoint = Instruction('ProfilePoint', 111, [UInt16], globals())

CreateClosure = Instruction(
    'CreateClosure', 112, [Reg8, Reg8, UInt16], globals()
)

CreateClosureLongIndex = Instruction(
    'CreateClosureLongIndex', 113, [Reg8, Reg8, UInt32], globals()
)

CreateClosure.operands[2].operand_meaning = OperandMeaning.function_id

CreateClosureLongIndex.operands[2].operand_meaning = OperandMeaning.function_id

CreateThis = Instruction('CreateThis', 114, [Reg8, Reg8, Reg8], globals())

SelectObject = Instruction('SelectObject', 115, [Reg8, Reg8, Reg8], globals())

LoadParam = Instruction('LoadParam', 116, [Reg8, UInt8], globals())

LoadParamLong = Instruction('LoadParamLong', 117, [Reg8, UInt32], globals())

LoadConstUInt8 = Instruction('LoadConstUInt8', 118, [Reg8, UInt8], globals())

LoadConstInt = Instruction('LoadConstInt', 119, [Reg8, Imm32], globals())

LoadConstDouble = Instruction(
    'LoadConstDouble', 120, [Reg8, Double], globals()
)

LoadConstBigInt = Instruction(
    'LoadConstBigInt', 121, [Reg8, UInt16], globals()
)

LoadConstBigIntLongIndex = Instruction(
    'LoadConstBigIntLongIndex', 122, [Reg8, UInt32], globals()
)

LoadConstBigInt.operands[1].operand_meaning = OperandMeaning.bigint_id

LoadConstBigIntLongIndex.operands[1].operand_meaning = OperandMeaning.bigint_id

LoadConstString = Instruction(
    'LoadConstString', 123, [Reg8, UInt16], globals()
)

LoadConstStringLongIndex = Instruction(
    'LoadConstStringLongIndex', 124, [Reg8, UInt32], globals()
)

LoadConstString.operands[1].operand_meaning = OperandMeaning.string_id

LoadConstStringLongIndex.operands[1].operand_meaning = OperandMeaning.string_id

LoadConstEmpty = Instruction('LoadConstEmpty', 125, [Reg8], globals())

LoadConstUndefined = Instruction('LoadConstUndefined', 126, [Reg8], globals())

LoadConstNull = Instruction('LoadConstNull', 127, [Reg8], globals())

LoadConstTrue = Instruction('LoadConstTrue', 128, [Reg8], globals())

LoadConstFalse = Instruction('LoadConstFalse', 129, [Reg8], globals())

LoadConstZero = Instruction('LoadConstZero', 130, [Reg8], globals())

CoerceThisNS = Instruction('CoerceThisNS', 131, [Reg8, Reg8], globals())

LoadThisNS = Instruction('LoadThisNS', 132, [Reg8], globals())

ToNumber = Instruction('ToNumber', 133, [Reg8, Reg8], globals())

ToNumeric = Instruction('ToNumeric', 134, [Reg8, Reg8], globals())

ToInt32 = Instruction('ToInt32', 135, [Reg8, Reg8], globals())

AddEmptyString = Instruction('AddEmptyString', 136, [Reg8, Reg8], globals())

GetArgumentsPropByValLoose = Instruction(
    'GetArgumentsPropByValLoose', 137, [Reg8, Reg8, Reg8], globals()
)

GetArgumentsPropByValStrict = Instruction(
    'GetArgumentsPropByValStrict', 138, [Reg8, Reg8, Reg8], globals()
)

GetArgumentsLength = Instruction(
    'GetArgumentsLength', 139, [Reg8, Reg8], globals()
)

ReifyArgumentsStrict = Instruction(
    'ReifyArgumentsStrict', 140, [Reg8], globals()
)

ReifyArgumentsLoose = Instruction(
    'ReifyArgumentsLoose', 141, [Reg8], globals()
)

CreateRegExp = Instruction(
    'CreateRegExp', 142, [Reg8, UInt32, UInt32, UInt32], globals()
)

CreateRegExp.operands[1].operand_meaning = OperandMeaning.string_id

CreateRegExp.operands[2].operand_meaning = OperandMeaning.string_id

SwitchImm = Instruction(
    'SwitchImm', 143, [Reg8, UInt32, Addr32, UInt32, UInt32], globals()
)

CreateGenerator = Instruction(
    'CreateGenerator', 144, [Reg8, Reg8, UInt16], globals()
)

CreateGeneratorLongIndex = Instruction(
    'CreateGeneratorLongIndex', 145, [Reg8, Reg8, UInt32], globals()
)

CreateGenerator.operands[2].operand_meaning = OperandMeaning.function_id

CreateGeneratorLongIndex.operands[
    2
].operand_meaning = OperandMeaning.function_id

IteratorBegin = Instruction('IteratorBegin', 146, [Reg8, Reg8], globals())

IteratorNext = Instruction('IteratorNext', 147, [Reg8, Reg8, Reg8], globals())

IteratorClose = Instruction('IteratorClose', 148, [Reg8, UInt8], globals())

Jmp = Instruction('Jmp', 149, [Addr8], globals())
JmpLong = Instruction('JmpLong', 150, [Addr32], globals())

JmpTrue = Instruction('JmpTrue', 151, [Addr8, Reg8], globals())
JmpTrueLong = Instruction('JmpTrueLong', 152, [Addr32, Reg8], globals())

JmpFalse = Instruction('JmpFalse', 153, [Addr8, Reg8], globals())
JmpFalseLong = Instruction('JmpFalseLong', 154, [Addr32, Reg8], globals())

JmpUndefined = Instruction('JmpUndefined', 155, [Addr8, Reg8], globals())
JmpUndefinedLong = Instruction(
    'JmpUndefinedLong', 156, [Addr32, Reg8], globals()
)

JLess = Instruction('JLess', 157, [Addr8, Reg8, Reg8], globals())
JLessLong = Instruction('JLessLong', 158, [Addr32, Reg8, Reg8], globals())

JNotLess = Instruction('JNotLess', 159, [Addr8, Reg8, Reg8], globals())
JNotLessLong = Instruction(
    'JNotLessLong', 160, [Addr32, Reg8, Reg8], globals()
)

JLessN = Instruction('JLessN', 161, [Addr8, Reg8, Reg8], globals())
JLessNLong = Instruction('JLessNLong', 162, [Addr32, Reg8, Reg8], globals())

JNotLessN = Instruction('JNotLessN', 163, [Addr8, Reg8, Reg8], globals())
JNotLessNLong = Instruction(
    'JNotLessNLong', 164, [Addr32, Reg8, Reg8], globals()
)

JLessEqual = Instruction('JLessEqual', 165, [Addr8, Reg8, Reg8], globals())
JLessEqualLong = Instruction(
    'JLessEqualLong', 166, [Addr32, Reg8, Reg8], globals()
)

JNotLessEqual = Instruction(
    'JNotLessEqual', 167, [Addr8, Reg8, Reg8], globals()
)
JNotLessEqualLong = Instruction(
    'JNotLessEqualLong', 168, [Addr32, Reg8, Reg8], globals()
)

JLessEqualN = Instruction('JLessEqualN', 169, [Addr8, Reg8, Reg8], globals())
JLessEqualNLong = Instruction(
    'JLessEqualNLong', 170, [Addr32, Reg8, Reg8], globals()
)

JNotLessEqualN = Instruction(
    'JNotLessEqualN', 171, [Addr8, Reg8, Reg8], globals()
)
JNotLessEqualNLong = Instruction(
    'JNotLessEqualNLong', 172, [Addr32, Reg8, Reg8], globals()
)

JGreater = Instruction('JGreater', 173, [Addr8, Reg8, Reg8], globals())
JGreaterLong = Instruction(
    'JGreaterLong', 174, [Addr32, Reg8, Reg8], globals()
)

JNotGreater = Instruction('JNotGreater', 175, [Addr8, Reg8, Reg8], globals())
JNotGreaterLong = Instruction(
    'JNotGreaterLong', 176, [Addr32, Reg8, Reg8], globals()
)

JGreaterN = Instruction('JGreaterN', 177, [Addr8, Reg8, Reg8], globals())
JGreaterNLong = Instruction(
    'JGreaterNLong', 178, [Addr32, Reg8, Reg8], globals()
)

JNotGreaterN = Instruction('JNotGreaterN', 179, [Addr8, Reg8, Reg8], globals())
JNotGreaterNLong = Instruction(
    'JNotGreaterNLong', 180, [Addr32, Reg8, Reg8], globals()
)

JGreaterEqual = Instruction(
    'JGreaterEqual', 181, [Addr8, Reg8, Reg8], globals()
)
JGreaterEqualLong = Instruction(
    'JGreaterEqualLong', 182, [Addr32, Reg8, Reg8], globals()
)

JNotGreaterEqual = Instruction(
    'JNotGreaterEqual', 183, [Addr8, Reg8, Reg8], globals()
)
JNotGreaterEqualLong = Instruction(
    'JNotGreaterEqualLong', 184, [Addr32, Reg8, Reg8], globals()
)

JGreaterEqualN = Instruction(
    'JGreaterEqualN', 185, [Addr8, Reg8, Reg8], globals()
)
JGreaterEqualNLong = Instruction(
    'JGreaterEqualNLong', 186, [Addr32, Reg8, Reg8], globals()
)

JNotGreaterEqualN = Instruction(
    'JNotGreaterEqualN', 187, [Addr8, Reg8, Reg8], globals()
)
JNotGreaterEqualNLong = Instruction(
    'JNotGreaterEqualNLong', 188, [Addr32, Reg8, Reg8], globals()
)

JEqual = Instruction('JEqual', 189, [Addr8, Reg8, Reg8], globals())
JEqualLong = Instruction('JEqualLong', 190, [Addr32, Reg8, Reg8], globals())

JNotEqual = Instruction('JNotEqual', 191, [Addr8, Reg8, Reg8], globals())
JNotEqualLong = Instruction(
    'JNotEqualLong', 192, [Addr32, Reg8, Reg8], globals()
)

JStrictEqual = Instruction('JStrictEqual', 193, [Addr8, Reg8, Reg8], globals())
JStrictEqualLong = Instruction(
    'JStrictEqualLong', 194, [Addr32, Reg8, Reg8], globals()
)

JStrictNotEqual = Instruction(
    'JStrictNotEqual', 195, [Addr8, Reg8, Reg8], globals()
)
JStrictNotEqualLong = Instruction(
    'JStrictNotEqualLong', 196, [Addr32, Reg8, Reg8], globals()
)

_opcode_to_instruction: Dict[int, Instruction] = {
    v.opcode: v for v in _instructions
}
_name_to_instruction: Dict[str, Instruction] = {
    v.name: v for v in _instructions
}

_builtin_function_names: List[str] = [
    'Array.isArray',
    'Date.UTC',
    'Date.parse',
    'JSON.parse',
    'JSON.stringify',
    'Math.abs',
    'Math.acos',
    'Math.asin',
    'Math.atan',
    'Math.atan2',
    'Math.ceil',
    'Math.cos',
    'Math.exp',
    'Math.floor',
    'Math.hypot',
    'Math.imul',
    'Math.log',
    'Math.max',
    'Math.min',
    'Math.pow',
    'Math.round',
    'Math.sin',
    'Math.sqrt',
    'Math.tan',
    'Math.trunc',
    'Object.create',
    'Object.defineProperties',
    'Object.defineProperty',
    'Object.freeze',
    'Object.getOwnPropertyDescriptor',
    'Object.getOwnPropertyNames',
    'Object.getPrototypeOf',
    'Object.isExtensible',
    'Object.isFrozen',
    'Object.keys',
    'Object.seal',
    'String.fromCharCode',
    'silentSetPrototypeOf',
    'requireFast',
    'getTemplateObject',
    'ensureObject',
    'getMethod',
    'throwTypeError',
    'copyDataProperties',
    'copyRestArgs',
    'arraySpread',
    'apply',
    'exportAll',
    'exponentiationOperator',
    'initRegexNamedGroups',
    'spawnAsync',
]
